[versions]
agp = "8.7.2"
kotlin = "2.0.21"
devtools = "2.0.21-1.0.27"
material = "1.12.0"
xposed = "82"
yukihookapi = "1.2.1"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed" }
yukihookapi-api = { module = "com.highcapable.yukihookapi:api", version.ref = "yukihookapi" }
yukihookapi-ksp-xposed = { module = "com.highcapable.yukihookapi:ksp-xposed", version.ref = "yukihookapi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools" }
